export enum routeName {
  SIGNIN = '/signin',
  DASHBOARD = '/dashboard',
  TOUR = '/tour',
  TOUR_BASIC = '/tour/basic',
  TOUR_PAYMENTS = '/tour/payments',
  TOUR_VENDORS = '/tour/vendors',
  TOUR_TRAVELLERS = '/tour/travellers',
  TOUR_BOOKINGS = '/tour/bookings',
  TOUR_FLIGHTS = '/tour/flights',
  TOUR_HOTELS = '/tour/hotels',
  TOUR_ITINERARY = '/tour/itinerary',
  ADD_TOUR = '/tour/add',
  VENDOR = '/vendor',
  ACCOUNT = '/accounts',
  ACCOUNT_DETAIL = '/accounts/:id',
  INSTITUTE = '/institute',
  INSTITUTE_DETAILS = '/institute/:id',
}
